### ISSUE TITLE
Pins

### ISSUE THREAD

**Issue by Madeleinfar** [daniel-leonard-robinson/Wireless-Gate-Controller#1]
Hi there, 
Do you by any chance have a schematic of your RL78G14 with all the input and output pins attached?
I'm a bit confused with which interrupt is used for what and I'm trying to understand why my code isn't working :)

**Comment by dan-leo** [comment]
Ah, I haven't made a schematic yet, but I will make a table shortly of all the pins I have used and their uses

**Comment by dan-leo** [comment]
What isn't working on your side? :)

**Comment by Madeleinfar** [comment]
Cool, I'm having trouble with my ADC since I added the remote software to
my project, and I have no idea why.. Which is why I'm using your code to
verify that there isn't some major issue that I have picked up along the
way... hope you don't mind! :)

**Comment by dan-leo** [comment]
I'm reading in adc values on more than one channel (4 channels to be precise, but only using the data from 2 at the moment).

But in your case I assume there might be pin/timer/interrupt conflict of some kind? 

I have added a pinout

**Comment by dan-leo** [comment]
(I've added a schematic and explained which interrupt is used for what :)
